load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "event",
    srcs = [
        "event.cpp",
    ],
    hdrs = [
        "event.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "gtest_helper",
    srcs = [
    ],
    hdrs = [
        "gtest_helper.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "os",
    srcs = [
    ],
    hdrs = [
        "os.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "raii_handle",
    srcs = [
    ],
    hdrs = [
        "raii_handle.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "scope_exit",
    srcs = [
    ],
    hdrs = [
        "scope_exit.h",
    ],
    visibility = ["//visibility:public"],
)
