load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "event",
    srcs = [
        "event.cpp",
    ],
    hdrs = [
        "common/event.h",
    ],
    strip_include_prefix = "/lib",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "gtest_helper",
    srcs = [
    ],
    hdrs = [
        "common/gtest_helper.h",
    ],
    strip_include_prefix = "/lib",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "os",
    srcs = [
    ],
    hdrs = [
        "common/os.h",
    ],
    strip_include_prefix = "/lib",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "raii_handle",
    srcs = [
    ],
    hdrs = [
        "common/raii_handle.h",
    ],
    strip_include_prefix = "/lib",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "scope_exit",
    srcs = [
    ],
    hdrs = [
        "common/scope_exit.h",
    ],
    strip_include_prefix = "/lib",
    visibility = ["//visibility:public"],
)
