load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
  name = "main",
  srcs = [
    "main.cpp",
  ],
  deps = [
    "//AsyncAsioServer/lib:console",
    "//AsyncAsioServer/lib:tcp_server",
  ],
)
