load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "job_multiplexor",
    srcs = [
    ],
    hdrs = [
        "job_multiplexor.h",
    ],
    visibility = ["//:__subpackages__"],
)
