load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "counted_generator",
  srcs = [
  ],
  hdrs = [
    "counted_generator.h",
  ],
  deps = [
    "@asio",
  ],
  visibility = ["//:__subpackages__"],
)

cc_library(
  name = "oddifier",
  srcs = [
  ],
  hdrs = [
    "oddifier.h",
  ],
  deps = [
    "@asio",
  ],
  visibility = ["//:__subpackages__"],
)

cc_library(
  name = "random_generator",
  srcs = [
  ],
  hdrs = [
    "random_generator.h",
  ],
  deps = [
    "@asio",
  ],
  visibility = ["//:__subpackages__"],
)

cc_library(
  name = "throttled_line_printer",
  srcs = [
  ],
  hdrs = [
    "throttled_line_printer.h",
  ],
  deps = [
    "@asio",
  ],
  visibility = ["//:__subpackages__"],
)
