load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "application",
    srcs = [
        "application.cpp",
    ],
    deps = [
        "//Gmock_bazel/lib:account",
        "//Gmock_bazel/lib:notifier",
    ],
)
