load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "event",
    srcs = [
        "Event.cpp",
    ],
    hdrs = [
        "Event.h",
    ],
    visibility = ["//:__subpackages__"],
)
