load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    url = "https://github.com/google/googletest/archive/release-1.10.0.zip",
    strip_prefix = "googletest-release-1.10.0",
    sha256 = "94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91",
)

local_repository(
    name = "binary_search",
    path = "../BinarySearch",
)

local_repository(
    name = "common",
    path = "../Common",
)

local_repository(
    name = "consumer_producer",
    path = "../ConsumerProducer",
)

local_repository(
    name = "gmock",
    path = "../Gmock",
)

local_repository(
    name = "logger",
    path = "../Logger",
)

local_repository(
    name = "shared_ptr",
    path = "../SharedPtr",
)
