load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "realign",
    hdrs = [
        "realign.h",
    ],
    deps = [
        "@Common//lib:raii_handle",
    ],
    visibility = ["//:__subpackages__"],
)
